# Generated by Django 5.0.4 on 2024-04-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_contributor_book_bookcontributor_book_contributors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='phoneNumber',
            field=models.CharField(help_text='The contact phone number for the contributor.', max_length=17),
        ),
    ]
