# Generated by Django 5.0.4 on 2024-05-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_contributor_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_edited',
            field=models.DateTimeField(help_text='The date and time the review was modified', null=True),
        ),
    ]
