# Generated by Django 5.0.4 on 2024-06-23 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_date_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='sample/'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(help_text='The Book this review is about', on_delete=django.db.models.deletion.CASCADE, to='reviews.book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(help_text='Review text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time the review was created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_edited',
            field=models.DateTimeField(help_text='Date and time the review was modified', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='Rating the reviewer has given'),
        ),
    ]
