# Generated by Django 5.0.4 on 2024-06-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_book_file_field_book_image_field_alter_review_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file_field',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_field',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='sample',
            field=models.FileField(blank=True, null=True, upload_to='book_samples/'),
        ),
    ]
